data:
  tsv_path: "./dataset/validated.tsv"
  audio_folder: "./dataset/clips/"
  spectrogram_cache_folder: "./cache/spectrogram_cache"
  test_size: 0.1
  max_target_len: 50
  chunk_size: 1000  # 一次並行處理多少個檔案

  audio_params:
      max_duration: 10       # 固定處理多少秒的音訊
      target_sr: 16000       # 取樣率
      frame_length: 400      # STFT 視窗大小
      frame_step: 160        # STFT 步長
      fft_length: 512        # FFT 點數

training:
  batch_size: 32
  val_batch_size: 4
  epochs: 10
  num_classes: 34

model:
  num_hid: 200
  num_head: 2
  num_feed_forward: 400
  num_layers_enc: 4
  num_layers_dec: 1

# parallel 參數: n_jobs 代表開幾條 process/CPU核心處理
parallel:
  n_jobs: 2
