data:
  tsv_path: "./dataset/validated.tsv"
  audio_folder: "./dataset/clips/"
  cache_folder: "./cache/spectrogram_cache"
  test_size: 0.1
  max_target_len: 50
  chunk_size: 10000  # 一次並行處理多少個檔案

training:
  batch_size: 32
  val_batch_size: 4
  epochs: 10
  num_classes: 34

model:
  num_hid: 200
  num_head: 2
  num_feed_forward: 400
  num_layers_enc: 4
  num_layers_dec: 1

# parallel 參數: n_jobs 代表開幾條 process/CPU核心處理
parallel:
  n_jobs: 2
