data:
  tsv_path: "./dataset/validated.tsv"
  audio_folder: "./dataset/clips/"
  test_size: 0.1
  max_target_len: 50

training:
  batch_size: 16
  val_batch_size: 4
  epochs: 10
  num_classes: 34

model:
  num_hid: 200
  num_head: 2
  num_feed_forward: 400
  num_layers_enc: 4
  num_layers_dec: 1
